table call_log
	lineageTag: fb51381d-8cd6-46bf-9d0d-0c2bcdd8adc0

	column Call_Id
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: cc3f0219-d1ac-4be5-8c04-4e0eeb5a83c1
		summarizeBy: none
		sourceColumn: Call_Id

		annotation SummarizationSetBy = Automatic

	column Agent
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 8151a6d1-d69a-4f4f-a28f-71f0930a52dd
		summarizeBy: none
		sourceColumn: Agent

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 1b150f03-393d-402c-bdfa-d33bf39947ff
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		sourceProviderType: time
		lineageTag: dfadb320-2c72-42ef-bc55-d57bcd6ae527
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Topic
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: a3b2505c-fdfa-470a-bab1-c8f167c7bef4
		summarizeBy: none
		sourceColumn: Topic

		annotation SummarizationSetBy = Automatic

	column Answered__Y_N_
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: da07baf6-b330-4897-a79a-d31fb3b84ce1
		summarizeBy: none
		sourceColumn: Answered__Y_N_

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c88e33ff-25e2-48c5-8f72-58bfb40d5d78
		summarizeBy: none
		sourceColumn: Resolved

		annotation SummarizationSetBy = Automatic

	column Speed_of_answer_in_seconds
		dataType: double
		formatString: 0
		lineageTag: f543a693-66bf-4a09-84f6-f46d180d2f0f
		summarizeBy: sum
		sourceColumn: Speed_of_answer_in_seconds

		annotation SummarizationSetBy = Automatic

	column AvgTalkDuration
		dataType: dateTime
		formatString: Long Time
		sourceProviderType: time
		lineageTag: effa1843-ed3b-4792-a75d-38ea1e10cc5b
		summarizeBy: none
		sourceColumn: AvgTalkDuration

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Satisfaction_rating
		dataType: double
		formatString: 0
		sourceProviderType: double
		lineageTag: c0ff3f6c-0e86-4439-b4eb-10a3bb8c7140
		summarizeBy: sum
		sourceColumn: Satisfaction_rating

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: dd1fc7e3-656a-4877-b1f5-77e117cf6754
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column AvgMinTalkDuration
		dataType: double
		isNullable: false
		sourceProviderType: double
		lineageTag: e8262de8-cdee-4d34-a0d0-cbe0fbdd2942
		summarizeBy: sum
		sourceColumn: AvgMinTalkDuration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESC_SATIS_CLIENTE =
			SWITCH(call_log[Satisfaction_rating],0,"NO RESPONDIO",
			                                                          1,"MUY DECEPCIONADO",
			                                                          2,"DECEPCIONADO",
			                                                          3,"LE DA IGUAL",
			                                                          4,"SATISFECHO",
			                                                          5,"MUY SATISFECHO")
		lineageTag: 45d78f47-7bd3-49e4-a345-a5e305313d28
		summarizeBy: none
		sortByColumn: Satisfaction_rating

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition call_log = m
		mode: import
		source =
				let
				    Origen = GoogleBigQuery.Database(),
				    #"data-competencia" = Origen{[Name="data-competencia"]}[Data],
				    call_center_datapath_Schema = #"data-competencia"{[Name="call_center_datapath",Kind="Schema"]}[Data],
				    call_log_Table = call_center_datapath_Schema{[Name="call_log",Kind="Table"]}[Data],
				    #"Valor reemplazado" = Table.ReplaceValue(call_log_Table,null,0,Replacer.ReplaceValue,{"Satisfaction_rating"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado",{{"Answered__Y_N_", type text}}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Tipo cambiado","false","N",Replacer.ReplaceText,{"Answered__Y_N_"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","true","S",Replacer.ReplaceText,{"Answered__Y_N_"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado2",{{"Resolved", type text}}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Tipo cambiado1","false","N",Replacer.ReplaceText,{"Resolved"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","true","S",Replacer.ReplaceText,{"Resolved"}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Valor reemplazado4", "Time", "Time - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"Time - Copia", "Hour"}}),
				    #"Hora extraída" = Table.TransformColumns(#"Columnas con nombre cambiado",{{"Hour", Time.Hour, Int64.Type}}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Hora extraída",{"Call_Id", "Agent", "Date", "Time", "Hour", "Topic", "Answered__Y_N_", "Resolved", "Speed_of_answer_in_seconds", "AvgTalkDuration", "Satisfaction_rating"}),
				    #"Filas ordenadas" = Table.Sort(#"Columnas reordenadas",{{"AvgTalkDuration", Order.Descending}}),
				    #"Columna duplicada1" = Table.DuplicateColumn(#"Filas ordenadas", "AvgTalkDuration", "AvgTalkDuration - Copia"),
				    #"Minuto extraído" = Table.TransformColumns(#"Columna duplicada1",{{"AvgTalkDuration - Copia", Time.Minute, Int64.Type}}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Minuto extraído",null,0,Replacer.ReplaceValue,{"AvgTalkDuration - Copia"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Valor reemplazado5",{{"AvgTalkDuration - Copia", "AvgMinTalkDuration"}}),
				    #"Columnas reordenadas1" = Table.ReorderColumns(#"Columnas con nombre cambiado1",{"Call_Id", "Agent", "Date", "Time", "Hour", "Topic", "Answered__Y_N_", "Resolved", "Speed_of_answer_in_seconds", "AvgTalkDuration", "AvgMinTalkDuration", "Satisfaction_rating"}),
				    #"Filas ordenadas1" = Table.Sort(#"Columnas reordenadas1",{{"Satisfaction_rating", Order.Ascending}}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Filas ordenadas1",null,#time(0, 0, 0),Replacer.ReplaceValue,{"AvgTalkDuration"}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6",null,0,Replacer.ReplaceValue,{"Speed_of_answer_in_seconds"})
				in
				    #"Valor reemplazado7"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

